import type { User, Task, Project, Transaction, Message, CalendarEvent } from '../types';

export const mockUsers: User[] = [
  { id: '1', name: 'Adi Pratama', email: 'adi@company.com', role: 'ceo' },
  { id: '2', name: 'Budi Santoso', email: 'budi@company.com', role: 'cto' },
  { id: '3', name: 'Citra Dewi', email: 'citra@company.com', role: 'cpo' },
  { id: '4', name: 'Dian Permata', email: 'dian@company.com', role: 'cmo' },
  { id: '5', name: 'Eka Rahayu', email: 'eka@company.com', role: 'cfo' },
  { id: '6', name: 'Fajar Nugroho', email: 'fajar@company.com', role: 'coo' },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Q4 Strategic Planning',
    description: 'Menyusun rencana strategis untuk Q4 2026',
    status: 'in_progress',
    priority: 'high',
    assignee: mockUsers[0],
    dueDate: new Date('2026-09-15'),
    createdAt: new Date('2026-08-01'),
    tags: ['strategy', 'planning'],
  },
  {
    id: '2',
    title: 'Implementasi Sistem CRM',
    description: 'Setup dan konfigurasi CRM untuk sales team',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[1],
    dueDate: new Date('2026-10-01'),
    createdAt: new Date('2026-08-10'),
    tags: ['tech', 'crm'],
  },
  {
    id: '3',
    title: 'Launch Campaign Digital Marketing',
    description: 'Campaign awareness produk baru di social media',
    status: 'review',
    priority: 'high',
    assignee: mockUsers[3],
    dueDate: new Date('2026-08-30'),
    createdAt: new Date('2026-08-05'),
    tags: ['marketing', 'campaign'],
  },
  {
    id: '4',
    title: 'Audit Keuangan Q3',
    description: 'Persiapan laporan keuangan untuk audit Q3',
    status: 'in_progress',
    priority: 'urgent',
    assignee: mockUsers[4],
    dueDate: new Date('2026-09-01'),
    createdAt: new Date('2026-08-15'),
    tags: ['finance', 'audit'],
  },
  {
    id: '5',
    title: 'Optimize Supply Chain',
    description: 'Evaluasi dan optimasi rantai pasok',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[5],
    dueDate: new Date('2026-10-15'),
    createdAt: new Date('2026-08-20'),
    tags: ['operations', 'supply-chain'],
  },
  {
    id: '6',
    title: 'Develop Mobile App MVP',
    description: 'Pembuatan MVP aplikasi mobile untuk customer',
    status: 'in_progress',
    priority: 'high',
    assignee: mockUsers[2],
    dueDate: new Date('2026-11-01'),
    createdAt: new Date('2026-07-15'),
    tags: ['product', 'development'],
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Digital Transformation 2026',
    description: 'Program transformasi digital menyeluruh',
    status: 'active',
    progress: 45,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    budget: 500000000,
    spent: 225000000,
    team: [mockUsers[0], mockUsers[1], mockUsers[2]],
  },
  {
    id: '2',
    name: 'Mobile App Launch',
    description: 'Peluncuran aplikasi mobile v1.0',
    status: 'active',
    progress: 30,
    startDate: new Date('2026-07-01'),
    endDate: new Date('2026-12-31'),
    budget: 200000000,
    spent: 60000000,
    team: [mockUsers[1], mockUsers[2]],
  },
  {
    id: '3',
    name: 'Brand Refresh',
    description: 'Rebranding dan update visual identity',
    status: 'completed',
    progress: 100,
    startDate: new Date('2026-03-01'),
    endDate: new Date('2026-06-30'),
    budget: 50000000,
    spent: 45000000,
    team: [mockUsers[3]],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'income',
    amount: 150000000,
    category: 'Penjualan',
    description: 'Pembayaran dari PT Maju Jaya',
    date: new Date('2026-08-20'),
    status: 'approved',
  },
  {
    id: '2',
    type: 'expense',
    amount: 25000000,
    category: 'Operasional',
    description: 'Biaya operasional bulanan',
    date: new Date('2026-08-15'),
    status: 'approved',
  },
  {
    id: '3',
    type: 'income',
    amount: 75000000,
    category: 'Service',
    description: 'Konsultasi IT untuk PT Sejahtera',
    date: new Date('2026-08-18'),
    status: 'pending',
  },
  {
    id: '4',
    type: 'expense',
    amount: 15000000,
    category: 'Marketing',
    description: 'Biaya campaign digital marketing',
    date: new Date('2026-08-12'),
    status: 'approved',
  },
  {
    id: '5',
    type: 'expense',
    amount: 50000000,
    category: 'Infrastructure',
    description: 'Pembelian server baru',
    date: new Date('2026-08-10'),
    status: 'approved',
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    content: 'Tim, minggu ini kita focus untuk closing deal dengan PT Maju Jaya.',
    sender: mockUsers[0],
    timestamp: new Date('2026-08-22T09:00:00'),
    channel: 'general',
  },
  {
    id: '2',
    content: 'Siap pak! Sales team sudah siap presentasi.',
    sender: mockUsers[3],
    timestamp: new Date('2026-08-22T09:05:00'),
    channel: 'general',
  },
  {
    id: '3',
    content: 'Progress CRM sudah 70%, insyaallah selesai minggu depan.',
    sender: mockUsers[1],
    timestamp: new Date('2026-08-22T09:10:00'),
    channel: 'tech',
  },
  {
    id: '4',
    content: 'Laporan keuangan Q3 sudah ready untuk review.',
    sender: mockUsers[4],
    timestamp: new Date('2026-08-22T09:15:00'),
    channel: 'finance',
  },
];

export const mockEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Board Meeting',
    description: 'Meeting bulanan dengan board of directors',
    start: new Date('2026-08-25T10:00:00'),
    end: new Date('2026-08-25T12:00:00'),
    type: 'meeting',
    attendees: [mockUsers[0], mockUsers[4], mockUsers[5]],
  },
  {
    id: '2',
    title: 'Product Launch Deadline',
    description: 'Deadline fitur MVP mobile app',
    start: new Date('2026-09-01'),
    end: new Date('2026-09-01'),
    type: 'deadline',
  },
  {
    id: '3',
    title: 'Team Building',
    description: 'Outing tim Q3',
    start: new Date('2026-08-28T08:00:00'),
    end: new Date('2026-08-28T17:00:00'),
    type: 'event',
    attendees: mockUsers,
  },
  {
    id: '4',
    title: 'Investor Pitch',
    description: 'Presentasi untuk investor seri A',
    start: new Date('2026-09-05T14:00:00'),
    end: new Date('2026-09-05T16:00:00'),
    type: 'meeting',
    attendees: [mockUsers[0], mockUsers[2], mockUsers[4]],
  },
];

